import { Menu } from './menu.model';

export const verticalMenuItems = [
    new Menu(1, 'Installment Receipt', '/repayment/installment-receipt', null, 'account_balance_wallet', null, false, 0),
    new Menu(2, 'Settlement', '/repayment/settlement', null, 'account_balance_wallet', null, false, 0),
    // new Menu(2, 'Reports', '/', null, 'keyboard', null, true, 0),
    new Menu(3, 'Account Statement/Installment Schedule', '/reports/installment-schedule-account-statement', null, 'account_balance', null, false, 0),
    // new Menu(4, 'Eligible customer ', '/report/eligible-customer-list', null, 'offline_pin', null, false, 2),
    // new Menu(6, 'Disbursement ', '/report/disbursement', null, 'monetization_on', null, false, 2),
    // new Menu(7, 'Collection ', '/report/collection', null, 'account_balance_wallet', null, false, 2),
     new Menu(8, 'Outstanding ', '/personal-report/outstanding', null, 'account_balance_wallet', null, false, 0),
    // new Menu(3, 'Account Statement ', '/report/acoount-statement', null, 'account_balance_wallet', null, false, 0),
    // new Menu(10, 'Excel Export ', '/report/excel-export', null, 'account_balance_wallet', null, false, 2),
    new Menu(9, 'Disbursement Cancel', '/personal-report/disbursement-cancel-request', null, 'account_balance_wallet', null, false, 0),
    new Menu(10, 'Disbursement Cancel Approval', '/personal-report/disbursement-cancel-approval', null, 'account_balance_wallet', null, false, 0),
    new Menu(11, 'Report', '/personal-report/report', null, 'account_balance_wallet', null, false, 0),
    new Menu(12, 'Detail Account Statement', '/personal-report/detail-account-statement', null, 'account_balance_wallet', null, false, 0),
    // new Menu(13, 'Manual Entry Request', '/repayment/manual-entry-request', null, 'account_balance_wallet', null, false, 0),
    // new Menu(13, 'Manual Entry Approval', '/repayment/manual-entry-approval', null, 'account_balance_wallet', null, false, 0),
    new Menu(13, 'Manual Entry', '/repayment/manual-entry', null, 'account_balance_wallet', null, false, 0),
    new Menu(14, 'PayU Updation', '/personal-report/payu-updation', null, 'account_balance_wallet', null, false, 0),
    new Menu(8, 'Due List', '/report/due-list', null, 'account_balance_wallet', null, false, 0),
    new Menu(8, 'Customer Outstanding Report', '/personal-report/customer-wise', null, 'account_balance_wallet', null, false, 0),
    //new Menu(8, 'Agreement', '/personal-report/agreement', null, 'account_balance_wallet', null, false, 0),
    new Menu(17, 'Download Agreement', '/personal-report/agreement-download', null, 'account_balance_wallet', null, false, 0),
    new Menu(17, 'Declaration', '/personal-report/declaration', null, 'account_balance_wallet', null, false, 0),
    new Menu(18, 'Disbursement Report', '/personal-report/disbursement-report', null, 'account_balance_wallet', null, false, 0),
    new Menu(19, 'RBI Report', '/personal-report/rbi-report', null, 'account_balance_wallet', null, false, 0),
    new Menu(20, 'Arbitration Report', '/personal-report/arbitration-report', null, 'account_balance_wallet', null, false, 0),
    new Menu(21, 'E Nach Presentation', '/personal-report/e-nach-presentation', null, 'account_balance_wallet', null, false, 0),
    new Menu(22, 'E Nach Realisation', '/personal-report/e-nach-realisation', null, 'account_balance_wallet', null, false, 0),
    // new Menu(22, 'E Nach Realisation', '/personal-report/e-nach-realisation', null, 'account_balance_wallet', null, false, 0),
    new Menu(23, 'E Nach Approval', '/personal-report/e-nach-disbursement-approval', null, 'account_balance_wallet', null, false, 0),
    new Menu(24, 'Eligibility Updation', '/personal-report/eligibility-updation', null, 'account_balance_wallet', null, false, 0),
    new Menu(25, 'Eligibility Approval', '/personal-report/eligibility-approval', null, 'account_balance_wallet', null, false, 0),
    new Menu(28, 'Collection Presentation', '/personal-report/collection-presentation', null, 'account_balance_wallet', null, false, 0),
    // new Menu(25, 'Eligibility Approval', '/personal-report/eligibility-approval', null, 'account_balance_wallet', null, false, 0),
    new Menu(27, 'Charges Bulk Upload', '/personal-report/charge-bulk-upload', null, 'account_balance_wallet', null, false, 0),
    new Menu(26, 'E-Nach Resend', '/personal-report/enach-resend', null, 'account_balance_wallet', null, false, 0),
    new Menu(29, 'Waiver Approval', '/personal-report/waiver-approval', null, 'account_balance_wallet', null, false, 0),
    new Menu(30, 'NOC', '/personal-report/noc', null, 'account_balance_wallet', null, false, 0),
    new Menu(31, 'Insurance', '/personal-report/insurance', null, 'account_balance_wallet', null, false, 0),
    new Menu(32, 'Bulk Upload', '/personal-report/bulk-upload', null, 'account_balance_wallet', null, false, 0),

    new Menu(33, 'Waiver Entry', '/personal-report/waiver-entry', null, 'account_balance_wallet', null, false, 0),
    new Menu(34, 'E Nach Url', '/personal-report/enachlink', null, 'account_balance_wallet', null, false, 0)


  
]
export const verticalMenuItems1 =[
    new Menu(1, 'Installment Receipt', '/repayment/installment-receipt', null, 'account_balance_wallet', null, false, 0),
    new Menu(1, 'Installment Receipt', '/repayment/installment-receipt', null, 'account_balance_wallet', null, false, 0),


]



export const horizontalMenuItems = [
    new Menu(1, 'Dashboard', '/', null, 'dashboard', null, false, 0),
    new Menu(2, 'Users', '/users', null, 'supervisor_account', null, false, 0),
    new Menu(3, 'UI Features', null, null, 'computer', null, true, 0),
    new Menu(4, 'Buttons', '/ui/buttons', null, 'keyboard', null, false, 3),
    new Menu(5, 'Cards', '/ui/cards', null, '', null, false, 3),
    new Menu(6, 'Lists', '/ui/lists', null, 'list', null, false, 3),
    new Menu(7, 'Grids', '/ui/grids', null, 'grid_on', null, false, 3),
    new Menu(8, 'Tabs', '/ui/tabs', null, 'tab', null, false, 3),
    new Menu(9, 'Expansion Panel', '/ui/expansion-panel', null, 'dns', null, false, 3),
    new Menu(10, 'Chips', '/ui/chips', null, 'label', null, false, 3),
    new Menu(11, 'Progress', '/ui/progress', null, 'data_usage', null, false, 3),
    new Menu(12, 'Dialog', '/ui/dialog', null, 'open_in_new', null, false, 3),
    new Menu(13, 'Tooltip', '/ui/tooltip', null, 'chat_bubble', null, false, 3),
    new Menu(14, 'Snackbar', '/ui/snack-bar', null, 'sms', null, false, 3),
    new Menu(16, 'Mailbox', '/mailbox', null, 'email', null, false, 40),
    new Menu(17, 'Chat', '/chat', null, 'chat', null, false, 40),
    new Menu(20, 'Form Controls', null, null, 'dvr', null, true, 0),
    new Menu(21, 'Autocomplete', '/form-controls/autocomplete', null, 'short_text', null, false, 20),
    new Menu(22, 'Checkbox', '/form-controls/checkbox', null, 'check_box', null, false, 20),
    new Menu(23, 'Datepicker', '/form-controls/datepicker', null, 'today', null, false, 20),
    new Menu(24, 'Form field', '/form-controls/form-field', null, 'view_stream', null, false, 20),
    new Menu(25, 'Input', '/form-controls/input', null, 'input', null, false, 20),
    new Menu(26, 'Radio button', '/form-controls/radio-button', null, 'radio_button_checked', null, false, 20),
    new Menu(27, 'Select', '/form-controls/select', null, 'playlist_add_check', null, false, 20),
    new Menu(28, 'Slider', '/form-controls/slider', null, 'tune', null, false, 20),
    new Menu(29, 'Slide toggle', '/form-controls/slide-toggle', null, 'star_half', null, false, 20),
    new Menu(30, 'Tables', null, null, 'view_module', null, true, 0),
    new Menu(31, 'Basic', '/tables/basic', null, 'view_column', null, false, 30),
    new Menu(32, 'Paging', '/tables/paging', null, 'last_page', null, false, 30),
    new Menu(33, 'Sorting', '/tables/sorting', null, 'sort', null, false, 30),
    new Menu(34, 'Filtering', '/tables/filtering', null, 'format_line_spacing', null, false, 30),
    new Menu(35, 'Selecting', '/tables/selecting', null, 'playlist_add_check', null, false, 30),
    new Menu(36, 'NGX DataTable', '/tables/ngx-table', null, 'view_array', null, false, 30),
    new Menu(70, 'Charts', null, null, 'multiline_chart', null, true, 0),
    new Menu(71, 'Bar Charts', '/charts/bar', null, 'insert_chart', null, false, 70),
    new Menu(72, 'Pie Charts', '/charts/pie', null, 'pie_chart', null, false, 70),
    new Menu(73, 'Line Charts', '/charts/line', null, 'show_chart', null, false, 70),
    new Menu(74, 'Bubble Charts', '/charts/bubble', null, 'bubble_chart', null, false, 70),
    new Menu(66, 'Maps', null, null, 'map', null, true, 70),
    new Menu(67, 'Google Maps', '/maps/googlemaps', null, 'location_on', null, false, 66),
    new Menu(68, 'Leaflet Maps', '/maps/leafletmaps', null, 'my_location', null, false, 66),
    new Menu(81, 'Drag & Drop', '/drag-drop', null, 'mouse', null, false, 3),
    new Menu(85, 'Material Icons', '/icons', null, 'insert_emoticon', null, false, 3),
    new Menu(40, 'Pages', null, null, 'library_books', null, true, 0),
    new Menu(43, 'Login', '/login', null, 'exit_to_app', null, false, 40),
    new Menu(44, 'Register', '/register', null, 'person_add', null, false, 40),
    new Menu(45, 'Blank', '/blank', null, 'check_box_outline_blank', null, false, 40),
    new Menu(46, 'Page Not Found', '/pagenotfound', null, 'error_outline', null, false, 40),
    new Menu(47, 'Error', '/error', null, 'warning', null, false, 40),
    new Menu(48, 'Landing', '/landing', null, 'filter', null, false, 40),
    new Menu(50, 'Schedule', '/schedule', null, 'event', null, false, 40),
    new Menu(200, 'External Link', null, 'http://themeseason.com', 'open_in_new', '_blank', false, 40)
]